//
//  LibreSSL.h
//  LibreSSL
//

#ifndef HEADER_LIBRESSL_H
#define HEADER_LIBRESSL_H

#if defined(__cplusplus)
#define LIBRESSL_EXTERN extern "C"
#else
#define LIBRESSL_EXTERN extern
#endif

LIBRESSL_EXTERN double LibreSSLVersionNumber;
LIBRESSL_EXTERN const unsigned char LibreSSLVersionString[];

#endif /* HEADER_LIBRESSL_H */

/* The following lines are auto generated by the Xcode script. Any changes
 * made after this point may be overwritten when the script is next run.
 */
