//
//  LibreSSL.h
//  LibreSSL
//

#ifndef _LIBRESSL_H
#define _LIBRESSL_H

#ifdef __cplusplus
extern "C" {
#endif

extern double LibreSSLVersionNumber;
extern const unsigned char LibreSSLVersionString[];

#ifdef __cplusplus
}
#endif

#endif /* _LIBRESSL_H */

/* The following lines are auto generated by the Xcode script. Any changes
 * made after this point may be overwritten when the script is next run.
 */
